### ISSUE TITLE
Pass cookies to external graphql on ssr

### ISSUE THREAD

**Issue by kyzia551** [reactql/example-auth#3]
Hello, Lee!
Thank you vey mutch for your great example!

My question a little bit outside. What to do if i use external graphQL endpoint? How to send cookie with JWT in case of server rendering?
I recieve it in koa, but can't understand how to pass cookie to graphQL request.

**Comment by leebenson** [comment]
If your GraphQL server/endpoint sends cookies, you'd need to edit `kit/entry/server.js` and change how the per-request Apollo client is instantiated, so that it could parse the cookie response, and then send _that_ as the JWT token. Everything after that point should be the same.
