### ISSUE TITLE
Replace isemail by validator

### ISSUE THREAD

**Issue by arsanjea** [reactql/example-auth#4]
Since validator.js is required for sequelize, why not add it as a project dependency and use it for email validation?

**Comment by leebenson** [comment]
sure, that's an option. I reached for the quickest email validator for this demo, but it could easily be swapped out. Happy to accept PRs.

**Comment by arsanjea** [comment]
by the way, I've emailed you to request the creation of a slack workspace for reactql but you haven't answered (sorry to be doing this via github).

**Comment by leebenson** [comment]
I saw it, thanks. Just busy catching up. Will respond soon.
