### ISSUE TITLE
Populating createdBy / author field?

### ISSUE THREAD

**Issue by robrobkay51** [reactql/example-auth#6]
Imagine you're persisting a new object to the database using a mutation (in this example it's a generic 'product') and you want to set a createdBy / author field to that of the current user. What is the recommended way of doing this?

For instance, I imagine you can use context to store current user id and then grab it in the GraphQL mutation (as below) but I guess this would be bad from a security perspective(?):

```
export const createProductMutation = {
  type: ProductResponseType,
  args: {
    title: {
      type: GraphQLString,
    },
    content: {
      type: GraphQLString,
    },
    createdBy: {
      type: GraphQLString,
    },
  },
  async resolve(_, args, ctx) {
    try {
      const product = await createProduct({ ...args, createdBy: ctx.state.[CURRENT_USER_ID] });
      return {
        ok: true,
        product,
      };
    } catch (e) {
      return {
        ok: false,
        errors: e,
      };
    }
  },
};
```

But, I guess you can also do this through GraphQL itself e.g. by setting the createdBy field on the ProductType to SessionType and access the current user that way? 

In addition, with Sequelize there's the getUser() function that comes built-in with associations.

So, I guess I'm just looking for a bit of guidance on what is the best route to go down here?

**Comment by leebenson** [comment]
As long as the user ID has been authenticated on the server, and it's 'tamper proof' (i.e. is passed as a JWT that can only be verified on the server), then it's perfectly acceptable to use that value inside of your mutations to attach DB records to that user -- in exactly the same way you would with a REST request or similar.

There's no security implication unless:

a) You are trusting the request to pass the `createdBy` field. This should always be server-side validated.

b) You are somehow bleeding that data out to the client - through Redux state, or similar.

It doesn't look like you're doing either of the above in your code example, so you're on the right track.
